create sequence hibernate_sequence start 1 increment 1;
create table course (id int8 not null, name varchar(255) not null, primary key (id));
create table course_aud (id int8 not null, rev int4 not null, revtype int2, name varchar(255), primary key (id, rev));
create table image (id int8 not null, location varchar(255), name varchar(255), primary key (id));
create table image_aud (id int8 not null, rev int4 not null, revtype int2, location varchar(255), name varchar(255), primary key (id, rev));
create table revinfo (rev int4 not null, revtstmp int8, primary key (rev));
create table student (balance int8 not null, birth_date date not null, external_id int4 not null, name varchar(255) not null, semester int4 not null, used_free_semesters int4 not null, id int8 not null, image_id int8, primary key (id));
create table student_aud (id int8 not null, rev int4 not null, balance int8, birth_date date, external_id int4, name varchar(255), semester int4, used_free_semesters int4, image_id int8, primary key (id, rev));
create table student_course (fk_student_id int8 not null, fk_course_id int8 not null, primary key (fk_student_id, fk_course_id));
create table student_course_aud (rev int4 not null, fk_student_id int8 not null, fk_course_id int8 not null, revtype int2, primary key (rev, fk_student_id, fk_course_id));
create table teacher (birth_date date not null, name varchar(255) not null, id int8 not null, primary key (id));
create table teacher_aud (id int8 not null, rev int4 not null, birth_date date, name varchar(255), primary key (id, rev));
create table teacher_course (fk_teacher_id int8 not null, fk_course_id int8 not null, primary key (fk_teacher_id, fk_course_id));
create table teacher_course_aud (rev int4 not null, fk_teacher_id int8 not null, fk_course_id int8 not null, revtype int2, primary key (rev, fk_teacher_id, fk_course_id));
create table user_security_aud (id int8 not null, rev int4 not null, revtype int2, facebook_id varchar(255), google_id varchar(255), password varchar(255), user_name varchar(255), primary key (id, rev));
create table user_security_roles_aud (rev int4 not null, user_security_id int8 not null, roles varchar(255) not null, revtype int2, primary key (rev, user_security_id, roles));
create table user_security (id int8 not null, facebook_id varchar(255), google_id varchar(255), password varchar(255), user_name varchar(255), primary key (id));
create table user_security_roles (user_security_id int8 not null, roles varchar(255));
alter table if exists course_aud add constraint FK7wota7b9g9bu9by751v8r8j65 foreign key (rev) references revinfo;
alter table if exists image_aud add constraint FKetc5y2t13bkdk5yuj4eswagd4 foreign key (rev) references revinfo;
alter table if exists student add constraint FK3mfbby9ahxvhsibdqwth1cvuc foreign key (image_id) references image;
alter table if exists student add constraint FK9un8hbwwcqi2s6oe939fmtnbc foreign key (id) references user_security;
alter table if exists student_aud add constraint FKpowh0gnunm9sdmlvra5j8qupq foreign key (id, rev) references user_security_aud;
alter table if exists student_course add constraint FK44ywy96s9lj9ayxo1kw6lviyk foreign key (fk_course_id) references course;
alter table if exists student_course add constraint FK301u6vomnhrsew7yj30r0lxwi foreign key (fk_student_id) references student;
alter table if exists student_course_aud add constraint FKorgxh6fw5qx5f60d6oew7v1iw foreign key (rev) references revinfo;
alter table if exists teacher add constraint FKqpw0hgd4q923o1vvgfksrnks3 foreign key (id) references user_security;
alter table if exists teacher_aud add constraint FKon3ae8cnhd00jo7j39uwtd09j foreign key (id, rev) references user_security_aud;
alter table if exists teacher_course add constraint FK40yvh6rnm26y0evgsye9g4bi5 foreign key (fk_course_id) references course;
alter table if exists teacher_course add constraint FKrcbeiujcq70rblpjyt792opbo foreign key (fk_teacher_id) references teacher;
alter table if exists teacher_course_aud add constraint FK6f5l42amlkdn88jgk3b02we2m foreign key (rev) references revinfo;
alter table if exists user_security_aud add constraint FKdk1qyvh7g7e0or22jm1k7ftpp foreign key (rev) references revinfo;
alter table if exists user_security_roles_aud add constraint FKh7ip5xn4vsolkk6dyxpeje9b foreign key (rev) references revinfo;
alter table if exists user_security_roles add constraint FKlrc77vgntcc77p1dsdwu6tqlq foreign key (user_security_id) references user_security;
